const messages = [
  "You are stronger than you think.",
  "Believe in yourself.",
  "You are capable of amazing things.",
  "Every day is a fresh start.",
  "You matter.",
  "You are beautiful inside and out.",
  "Difficult roads lead to beautiful destinations.",
  "Keep going, you're doing great!",
  "You're not alone.",
  "Smile, it suits you!",
  "Your potential is endless.",
  "This too shall pass.",
  "You're a fighter.",
  "Good things are coming.",
  "Stay positive, work hard, make it happen.",
  "You have the power to create change.",
  "Take a deep breath, you’ve got this.",
  "Be kind to yourself.",
  "Progress, not perfection.",
  "You are enough.",
  "You can do hard things.",
  "Your smile lights up the room.",
  "You’re doing better than you think.",
  "Keep pushing forward.",
  "Your journey is unique.",
  "Don’t give up.",
  "You are not defined by your past.",
  "You’ve come so far already.",
  "Celebrate small victories.",
  "One step at a time.",
  "You are inspiring.",
  "Kindness is your superpower.",
  "Breathe in courage, breathe out fear.",
  "You radiate positivity.",
  "You’re unstoppable.",
  "Your dreams are valid.",
  "You deserve happiness.",
  "You are loved.",
  "Today is your day.",
  "The world is better with you in it.",
  "You can handle whatever comes your way.",
  "Keep shining.",
  "Never stop believing.",
  "Let your light shine.",
  "You bring joy.",
  "You're a gift to this world.",
  "Trust the timing of your life.",
  "Rise by lifting others.",
  "You are a blessing."
];
const display = document.getElementById("motivational-message");
const randomMessage = messages[Math.floor(Math.random() * messages.length)];
display.textContent = randomMessage;
